services:
  - type: web
    name: smart-rent-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: smart-rent-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://smartrentsystem.netlify.app
